# Accepting array values from user

In [6]:
from array import *
vals=array('i',[])
a=int(input("Enter no of values in array: "))
for i in range(a):
    z=int(input("enter the next value: "))
    vals.append(z)
    

Enter no of values in array: 4
enter the next value: 1
enter the next value: 2
enter the next value: 3
enter the next value: 4


# Searching the values

In [11]:
from array import *
vals=array('i',[])
a=int(input("Enter no of values in array: "))
for i in range(a):
    z=int(input("enter the next value: "))
    vals.append(z)
    

vals1=int(input("Enter the values to be searched: "))
k=0
for j in vals:
    if j==vals1:
        print(k)
        break
        
    k+=1

Enter no of values in array: 4
enter the next value: 1
enter the next value: 2
enter the next value: 3
enter the next value: 4
Enter the values to be searched: 3
2


In [13]:
print(vals.index(vals1))

2


When you import numpy you can work with 2d arrays and moreover you need not specify the type code of variable

In [16]:
from numpy import *

arr=array([1,2,3,4,5,6])

print(arr)

[1 2 3 4 5 6]


# Ways of creating an array


In [18]:
a1=array([1,2,3])
print(a1)
print(a1.dtype)

[1 2 3]
int32


linspace()

Linspace() does consists of 3 parameters first two start and stop values and third one is step function based on which array is equally divided

In [20]:
a2=linspace(0,10,5)
print(a2)

[ 0.   2.5  5.   7.5 10. ]


# Arange()

In [21]:
a3=arange(1,15,2)
print(a3)

[ 1  3  5  7  9 11 13]


Differenceof numbers would be the step value given from start to stop values

# logspace

In [22]:
a4= logspace(1,40,5)
print(a4)

[1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]


# Copying an array

In [27]:
a5=array([1,2,3,4,5])
print(sin(a5))
print(cos(a5))
print(sqrt(a5))
a6=array([6,7,8,9,10])
print(a6)

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[1.         1.41421356 1.73205081 2.         2.23606798]
[ 6  7  8  9 10]


In [32]:
print(id(a5))
print(id(a6))
a6=a5
print(a5)
print(a6)
#shallowcopy
a6=a5.view()
print(a5)
print(a6)
print(id(a5))
print(id(a6))
#deepcopy
a6=a5.copy()
print(a5)
print(a6)
print(id(a5))
print(id(a6))

2140880202288
2140863477920
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
2140880202288
2140880294176
[1 2 3 4 5]
[1 2 3 4 5]
2140880202288
2140880294576


# Working with matrix


In [44]:
a7=array([[1,2,3,11,23,34],[4,5,6,12,13,14]])
print(a7)
#gives the datatype
print(a7.dtype)
#gives the dimensions of array
print(a7.ndim)
#gives the size of the array
print(a7.size)
#converts a n dimensional array into single dimensional array
a8=a7.flatten()
print(a8)
a9=a7.reshape(3,4)
print(a9)
a10=a7.reshape(2,2,3)
print(a10)

[[ 1  2  3 11 23 34]
 [ 4  5  6 12 13 14]]
int32
2
12
[ 1  2  3 11 23 34  4  5  6 12 13 14]
[[ 1  2  3 11]
 [23 34  4  5]
 [ 6 12 13 14]]
[[[ 1  2  3]
  [11 23 34]]

 [[ 4  5  6]
  [12 13 14]]]


In [50]:
m=matrix('1 2 3;4 5 6;7 8 9')
print(m)
print(diagonal(m))
print(m.max())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]
9


In [52]:
m1=m
m2=m*m1
print(m2)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
